### ISSUE TITLE
Bug im Tutorial wegen dem Buchmenü

### ISSUE THREAD

**Issue by Zartrix** [Glowdragon/GlowarionIssues#129]
Reminder für Glow.
Gefunden von unmut.

**Comment by Zartrix** [comment]
Bug wurde behoben/umgangen. Gesagter Spieler hat herausgefunden dass dieser bug nur in der 1.13 vorkommt, nachdem er mit der 1.12 mal gejoint ist. Der "Okay" button war in der 1.13 nicht vorhanden, weshalb er nicht aus dem Dialogfeld heraus konnte. Alles funktioniert jetzt für ihn.

**Comment by Glowdragon** [comment]
Behoben.
