### ISSUE TITLE
Items aus dem Gamemode

### ISSUE THREAD

**Issue by GlowarionHelfer** [Glowdragon/GlowarionIssues#130]
Mit dem Supportcharakter ist es möglich, in der Wildnis mit Gamemode Blöcke zu platzieren/abzubauen (alle Wildniswelten, wie Nether, betroffen). Durch Platzieren eines Items in einen Itemframe und durch Abbauen mit dem normalen Testcharakter ist Itemcheating möglich. Desweiteren können mit Supportcharakter andere Spieler in der Wildnis geschlagen werden.

**Comment by Glowdragon** [comment]
Nicht mehr relevant, da wir auf Hytale umsteigen.
