### ISSUE TITLE
Duplizieren von Schildern durch Mietplatz erstellen

### ISSUE THREAD

**Issue by Zartrix** [Glowdragon/GlowarionIssues#134]
Sobald ein Mietplatz erstellt wird bekommt man ein "Free Schild". Wenn man jedoch den Mietplatz löscht, kann man dieses Schild abbauen sogesehen ein kleiner Duplizier-bug.
Gefunden von Chroern.

**Comment by Glowdragon** [comment]
Es sollen grundsätzlich nicht zu häufig Mietplätze oder Grundstücke erstellt und gelöscht werden, weil dadurch IDs verschwendet werden. Man könnte für das Erstellen eines Mietplatzes eine kleine Gebühr verlangen.

**Comment by Glowdragon** [comment]
Nicht mehr relevant, da wir auf Hytale umsteigen.
