### ISSUE TITLE
Editierbare Schilder

### ISSUE THREAD

**Issue by Zartrix** [Glowdragon/GlowarionIssues#138]
Mit einem Schild im Inventar wird auf auf ein bereits gesetztes Schild "Gerechtsklickt".
Die Schild-GUI öffnet sich und man kann das gesetzte Schild bearbeiten.
"/schild" sollte demnach nur für Teammitglieder verfügbar sein (oder für irgendeinen besonderen Rang) und, dass beschriebene feature, für Spieler.

**Comment by Glowdragon** [comment]
Nicht mehr relevant, da wir auf Hytale umsteigen.
